version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tinnguyen
      POSTGRES_PASSWORD: toiyeuvietnam
      POSTGRES_DB: main
    ports:
      - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
